### ISSUE TITLE
Redis going mad on armhf

### ISSUE THREAD

**Issue by leolivier** [docker-library/redis#269]
Hi 
I initially filled an issue on mailu's github here: https://github.com/Mailu/Mailu/issues/1752 
Reissuing here as it's a redis issue:
I'm using two different containers with the latest redis for armv7/armhf image, one for mailu, and one for nextcloud.
Everything went fine (and for several months) until the latest version but now the latest redis image for armhf is going mad and eats a lot of CPU:
```
top - 16:23:19 up 14:21,  2 users,  load average: 3,56, 3,98, 4,75
Tasks: 310 total,   2 running, 307 sleeping,   0 stopped,   1 zombie
%Cpu(s): 16,6 us, 64,5 sy,  0,0 ni, 18,0 id,  0,6 wa,  0,0 hi,  0,2 si,  0,0 st
MiB Mem :   1866,5 total,    153,9 free,   1212,9 used,    499,8 buff/cache
MiB Swap:   2048,0 total,   1713,6 free,    334,4 used.    521,6 avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                                                                                                                               
27658 999       20   0   31828   6324   3056 R 186,1   0,3  17:08.16 redis-server                                                                                                                          
 4626 999       20   0   26484   1068    552 S  93,1   0,1 182:16.36 redis-server                                                                                                                          
 1956 pi        20   0   82100   5900   2972 S  13,9   0,3  24:52.84 gvfs-udisks2-vo                                                                                                                       
28229 www-data  20   0  250344  29028  20316 S   5,6   1,5   0:32.96 apache2                                                                                                                               
    1 root      20   0   33912   5712   3880 S   2,0   0,3   6:54.93 systemd                                                                                                                               
```

If I strace it, I get a lot of errors saying : 
```
syscall_0x193(0, 0xbed1fba0, 0, 0xbed1fba0, 0x193, 0xbed1fdc4) = -1 EPERM (Opération non permise)
epoll_pwait(5, [], 10128, 0, NULL, 8)   = 0
syscall_0x193(0, 0xbed1fc60, 0, 0xbed1fc60, 0x193, 0xb6cd0e10) = -1 EPERM (Opération non permise)
syscall_0x193(0, 0xbed1fc60, 0, 0xbed1fc60, 0x193, 0xb6cd0e10) = -1 EPERM (Opération non permise)
syscall_0x193(0, 0xbed1fc60, 0, 0xbed1fc60, 0x193, 0xbed1fdc4) = -1 EPERM (Opération non permise)
syscall_0x193(0, 0xbed1fba0, 0, 0xbed1fba0, 0x193, 0xbed1fdc4) = -1 EPERM (Opération non permise)
epoll_pwait(5, [], 10128, 0, NULL, 8)   = 0
syscall_0x193(0, 0xbed1fc60, 0, 0xbed1fc60, 0x193, 0xb6cd0e10) = -1 EPERM (Opération non permise)
syscall_0x193(0, 0xbed1fc60, 0, 0xbed1fc60, 0x193, 0xb6cd0e10) = -1 EPERM (Opération non permise)

```

## Logs
nothing special in the logs:
```
pi@raspberrypi /docker/mailu $ docker logs mailu.redis --tail 100
1:C 13 Jun 2071 14:32:40.000 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 13 Jun 2071 14:32:40.000 # Redis version=6.0.10, bits=32, commit=00000000, modified=0, pid=1, just started
1:C 13 Jun 2071 14:32:40.000 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
1:M 13 Jun 2071 14:29:12.000 # Warning: 32 bit instance detected but no memory limit set. Setting 3 GB maxmemory limit with 'noeviction' policy now.
1:M 13 Jun 2071 14:31:52.000 * Running mode=standalone, port=6379.
1:M 13 Jun 2071 14:32:40.000 # Server initialized
1:M 13 Jun 2071 14:07:20.000 * Loading RDB produced by version 6.0.10
1:M 13 Jun 2071 14:07:20.000 * RDB age -1612653112 seconds
1:M 13 Jun 2071 14:07:20.000 * RDB memory usage when created 2.38 Mb
1:M 13 Jun 2071 14:30:48.000 * DB loaded from disk: -0.007 seconds
1:M 13 Jun 2071 14:32:40.000 * Ready to accept connections
```

I used the webhippie/redis image to check and it's working fine with that image.
I'm not the only one with this issue, please see https://github.com/Mailu/Mailu/issues/1752 

Thanks for fixing that.

**Comment by oranagra** [comment]
@leolivier can you try getting stack trace from redis a few times, to see what it's doing? something like `gdb -batch -ex "bt" -p <pid>`
and maybe also check if it's eating stime or utime?

btw, something seems very wrong with the clock, note the timestamps are for `2071` and the rdb loading time is `-0.007 seconds`

**Comment by leolivier** [comment]
Hi @oranagra 
I tried to gdb several times, the redis container from the host, I get systematically this:
```
warning: Target and debugger are in different PID namespaces; thread lists and other data are likely unreliable.  Connect to gdbserver inside the container.
0xb6f5e904 in epoll_pwait () from target:/lib/ld-musl-armhf.so.1
#0  0xb6f5e904 in epoll_pwait () from target:/lib/ld-musl-armhf.so.1
#1  0xb6f5e92a in epoll_wait () from target:/lib/ld-musl-armhf.so.1
#2  0x0045c70c in aeApiPoll (tvp=<optimized out>, eventLoop=0xb6940380) at ae_epoll.c:112
#3  aeProcessEvents (eventLoop=eventLoop@entry=0xb6940380, flags=flags@entry=27) at ae.c:447
#4  0x0045cac0 in aeMain (eventLoop=0xb6940380) at ae.c:539
#5  0x0045a148 in main (argc=<optimized out>, argv=0xbe9a2dc4) at server.c:5498
[Inferior 1 (process 11315) detached]

```
and the debugger stops. I can't run it from the container where gdb is not installed (or should I install it?)

The stack confirms it's stuck in the epoll_pwait as described in the strace in my previous post.
Also, if you google syscall_0x193 that's in this strace, you find it's linked to the clock_gettime syscall (e.g. https://sourceware.org/pipermail/glibc-cvs/2020q1/068430.html) so it's not that strange that there are some clock issues  in the logs.
Nevertheless, I don't have these clock errors in other containers which run fine and if I start the webhippie image, everything works fine for redis too...

For the different times eaten:
```
pi@raspberrypi /docker/mailu $ ps -o pid,comm,lstart,etime,time,utime,stime,args -p 11315
  PID COMMAND                          STARTED     ELAPSED     TIME  UTIME STIME COMMAND
11315 redis-server    Fri Feb 12 17:19:19 2021       22:00 00:21:13      - 17:19 redis-server

```
so again, everything in the system in this syscall error...

**Comment by tianon** [comment]
Sounds like you're using the Alpine variants of the image, which recently upgraded to Alpine 3.13 (https://github.com/docker-library/redis/pull/264).

The underlying issue is tracked at https://github.com/moby/moby/issues/40734, but the short version is that you need to update libseccomp on your host to 2.4.2 or newer and Docker to 19.03.9 or newer.

See also https://wiki.alpinelinux.org/wiki/Release_Notes_for_Alpine_3.13.0#time64_requirements.

**Comment by leolivier** [comment]
Thanks a lot @tianon for pointing the solution.
For those who want to know how to proceed for upgrading libseccomp: https://hotio.dev/libseccomp2-saga/
In short: 
```
wget http://ftp.us.debian.org/debian/pool/main/libs/libseccomp/libseccomp2_2.5.1-1_armhf.deb
sudo dpkg -i libseccomp2_2.5.1-1_armhf.deb 
```
